---
title: "f"
author: "Ben Nolan and  Nicholas Waters"
date: "10/7/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
we makde a data


```{r}
dirpath <- "./docs/microbiome2/"
filtpath <- "./docs/microbiome2/clean/"
dir.create(filtpath)
mb_meta <- read.csv("./docs/microbiome2/SraRunTable-PRJNA530262.txt", stringsAsFactors = F)

ft <- mb_meta[mb_meta$host_trimester == 1, ]
table(ft$host_group)

write.table(ft$Run, "./docs/microbiome2/first_tri_runs", col.names = F, row.names = F)

```
  
```{bash}
while read x; do fasterq-dump --split-files $x ; done < microbiome2/first_tri_runs

```
  
  ```{r}
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs <- sort(list.files(dirpath, pattern="_1.fastq", full.names = TRUE))
fnRs <- sort(list.files(dirpath, pattern="_2.fastq", full.names = TRUE))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)


plotQualityProfile(fnFs)
plotQualityProfile(fnRs[1:2])

# Place filtered files in filtered/ subdirectory
filtFs <- file.path(filtpath, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filtpath,  paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
head(out)

errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)

dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
```